// Extra quick answers for Fitso's built-in coach. Each entry matches when every keyword group
// has at least one hit (with small typo tolerance for longer words).
export interface Faq {
  id: string;
  any: string[][];
  a: string;
  /** specific enough to beat a general topic answer (e.g. "whey + hair fall") */
  strong?: boolean;
  chips?: string[];
}

export const FAQ: Faq[] = [
  { id: "eggs-yolk", strong: true, any: [["egg", "eggs", "anda", "ande"], ["yolk", "yellow", "whole", "bad", "cholesterol", "how many", "per day", "daily", "a day"]], a: "Whole eggs are great. The yolk has most of the vitamins, choline and healthy fats. For healthy people, **2–3 whole eggs a day is fine** (research shows dietary cholesterol has a small effect on blood cholesterol for most people). Want more protein without the fat? Add extra egg whites. If you have high cholesterol or heart disease, follow your doctor's limit.", chips: ["Cheap high-protein foods", "How much protein do I need?"] },
  { id: "ghee", any: [["ghee", "butter", "makhan"]], a: "Ghee isn't the enemy. It's just calorie-dense: 1 tsp is about 45 kcal. **1–2 teaspoons a day** fits easily into most diets and adds flavour. The problem is only when it's poured freely. Losing fat? Measure it rather than skipping it completely." },
  { id: "milk-night", any: [["milk", "doodh", "haldi"], ["night", "bed", "sleep", "raat"]], a: "Milk at night is perfectly fine. It has slow-digesting casein protein that helps overnight recovery, and a warm glass (haldi doodh too) can help you relax. It only matters for your total daily calories, not the time. Lactose trouble? Try curd or lactose-free milk." },
  { id: "banana", any: [["banana", "kela", "bananas"]], a: "Bananas are a great pre-workout food: quick energy, potassium, about 100 kcal each. They don't \"make you fat\"; total calories do. 1–2 a day is fine whether you're losing fat or gaining. For weight gain, blend them with milk and peanut butter." },
  { id: "green-tea", any: [["green tea", "black coffee", "coffee"]], a: "Green tea and black coffee have tiny fat-burning effects, about 50–100 kcal a day at most. They're fine as low-calorie drinks, and caffeine before a workout can boost performance. They won't replace a calorie deficit though. Avoid caffeine after about 2 pm so it doesn't hurt your sleep." },
  { id: "detox", any: [["apple cider", "detox", "lemon water", "jeera water", "methi water", "honey lemon", "warm water", "cleanse"]], a: "Honest answer: detox drinks, lemon-honey water, ACV and jeera water don't burn fat. Your liver and kidneys already detox you for free. They're fine as low-calorie drinks if you enjoy them, but fat loss comes from a small calorie deficit, protein, movement and sleep." },
  { id: "rice-timing", any: [["rice", "chawal"], ["night", "dinner", "raat", "daily", "every day"]], a: "Rice at night is fine. Timing doesn't make you gain fat; portion and total calories do. Stick to about a fist-sized portion, pair it with dal, sabzi and a protein, and you're good." },
  { id: "late-eating", any: [["night", "late", "after 8", "raat", "dinner late"], ["eat", "food", "fruit", "fruits", "khana", "dinner", "rice"]], a: "Eating late doesn't magically add fat; total calories over the day matter most. That said, a lighter dinner 2–3 hours before bed usually means better sleep and less late-night snacking. Fruit at night is completely fine." },
  { id: "height", strong: true, any: [["height", "lamba", "taller", "tall"]], a: "Height is mostly set by genetics, and once your growth plates close (usually by 18–21) exercise can't make you taller. What you can do: **fix your posture**, which often adds 1–3 cm of visible height, sleep well, and eat enough protein and calcium if you're still growing. Hanging or stretching won't lengthen bones, whatever ads claim.", chips: ["Shoulders & posture workout"] },
  { id: "stamina", any: [["stamina", "endurance", "breathless", "get tired", "tired quickly", "saans", "phool"]], a: "Stamina builds fast with regular cardio:\n\n- **3–4 sessions a week** of brisk walking, jogging, cycling or skipping, 20–40 minutes\n- **Mostly easy pace** (you can still talk), plus **one interval session**: 30 sec fast, 60 sec easy, ×8\n- Add 10% more time each week\n- Sleep well and don't skip carbs on training days\n\nMost people notice a big difference in **3–4 weeks**.", chips: ["Skipping & cardio workout", "How many steps a day?"] },
  { id: "pushups", strong: true, any: [["push up", "pushup", "push-up", "pushups", "push ups"], ["more", "increase", "cant", "can t", "improve", "first", "one", "zero", "how to"]], a: "To do more push-ups:\n\n1. Start with **incline push-ups** (hands on a bed or table) and knee push-ups\n2. Do **3–4 sets, 3 times a week**, stopping 1–2 reps before failure\n3. Lower the incline every week or two until you reach the floor\n4. Add slow negatives: lower yourself over 3–5 seconds\n\nKeep your body straight like a plank and elbows at about 45°. Try the **Push-Up Chest Builder** workout in the app.", chips: ["Push-up chest workout", "Beginner home workout"] },
  { id: "pullups", strong: true, any: [["pull up", "pullup", "pull-up", "pullups", "chin up", "chinup"]], a: "Your first pull-up:\n\n- **Dead hangs** for 20–30 sec to build grip\n- **Negatives:** jump to the top and lower yourself slowly over 3–5 sec, 3–5 reps\n- **Lat pulldowns and rows**, 3× a week, to build pulling strength\n- **Band-assisted pull-ups** if your gym has bands\n\nLosing a few kg of fat also makes them much easier. Most people get their first rep in 4–8 weeks." },
  { id: "reps-sets", any: [["how many reps", "how many sets", "reps and sets", "sets and reps", "rep range", "kitne set", "kitne rep"]], a: "Simple guide:\n\n- **Strength:** 3–5 sets of 3–6 reps, heavy, with 2–3 min rest\n- **Muscle:** 3–4 sets of 6–15 reps, rest 60–120 sec\n- **Endurance/toning:** 2–3 sets of 15–20 reps, rest 30–60 sec\n\nThe key in every case is finishing each set **1–3 reps short of failure**, and doing a bit more over time (more weight or reps). Aim for **10–20 hard sets per muscle per week**.", chips: ["Make me a 4-day gym plan"] },
  { id: "rest-sets", any: [["rest between", "between sets", "rest time", "how long rest", "kitna rest"]], a: "Rest **2–3 minutes** between heavy compound sets (squats, deadlifts, bench) and **60–90 seconds** for smaller exercises (curls, raises). Short on time? Pair exercises for different muscles, like a press and a row, and rest between rounds. The app's rest timer on the Train tab does this for you." },
  { id: "failure", any: [["failure", "deload", "overtraining", "overtrain"]], a: "You don't need to train to failure every set. Stopping 1–3 reps short gives nearly the same muscle growth with less fatigue and injury risk. Save failure for the last set of smaller exercises.\n\nIf you're always tired, your lifts are dropping and you're sleeping badly, take a **deload week**: same exercises, about half the sets and lighter weights, then build back up." },
  { id: "sick", strong: true, any: [["fever", "cold", "cough", "sick", "ill", "bukhar", "flu", "covid", "infection", "viral"]], a: "Use the **neck check**: symptoms only above the neck (runny nose, mild sore throat) means light exercise like a walk or easy yoga is usually okay. Symptoms **below the neck** (fever, body ache, chest congestion, stomach upset) mean **rest completely** until the fever has been gone for 24–48 hours, then return gradually over a week. Drink plenty of fluids and see a doctor if the fever is high or lasts more than 2–3 days." },
  { id: "smoking", any: [["smoke", "smoking", "cigarette", "cigarettes", "vape", "vaping", "gutka", "tobacco"]], a: "Smoking and tobacco hurt your stamina, recovery, lungs and heart, and slow muscle healing. The good news: lung function and stamina start improving within weeks of quitting. Exercise helps with cravings too. Free help in India: the **National Tobacco Quitline 1800-112-356**. You've got this. 💪" },
  { id: "hairfall", strong: true, any: [["hair fall", "hair loss", "baal", "hairfall", "balding"]], a: "Gym itself doesn't cause hair fall, and neither do whey or creatine in normal doses (the creatine link is based on one small study that's never been repeated). Common real causes: very low-calorie diets, low protein, iron, vitamin D or B12 deficiency, stress, thyroid, and genetics. Eat enough protein, avoid crash diets, and get a blood test if it's sudden or heavy." },
  { id: "skin", any: [["stretch marks", "loose skin", "saggy skin", "acne", "pimples"]], a: "**Loose skin** after fat loss improves with slow, steady weight loss, strength training (muscle fills the space) and time. It's usually much less than people fear unless the loss is very large. **Stretch marks** fade from red to silver over months; moisturiser helps comfort, but no cream fully removes them. For **acne**, check sugary foods, dairy or poor-quality whey, and see a dermatologist if it persists." },
  { id: "fasting-religious", strong: true, any: [["navratri", "ramadan", "roza", "rozas", "vrat", "upvas", "fasting day", "ekadashi"]], a: "Training while fasting (Navratri, Ramadan, vrat):\n\n- Keep workouts **lighter and shorter** (30–45 min); focus on maintaining, not personal bests\n- **Best time:** about an hour before breaking the fast, or 1–2 hours after eating\n- At eating times: protein (paneer, curd, milk, makhana, sabudana with peanuts, eggs/meat if allowed), fruit, and lots of water\n- Stop if you feel dizzy, and skip intense cardio on long dry fasts\n\nDiabetic or on medication? Check with your doctor before fasting." },
  { id: "squat-form", any: [["squat", "squats"], ["how", "form", "technique", "correct", "properly", "right way", "kaise"]], a: "Good squat form:\n\n1. Feet **shoulder-width**, toes slightly out\n2. Brace your belly, chest up, eyes forward\n3. **Sit back and down** between your heels; knees track over your toes (it's fine if they go a little past)\n4. Go as deep as you can with a **flat back**, ideally thighs parallel or lower\n5. Drive up through your **whole foot**, squeezing your glutes\n\nStart with bodyweight or goblet squats. The app's Goblet Squat and Bodyweight Squat demos show the movement.", chips: ["My knees hurt when I squat"] },
  { id: "deadlift-form", any: [["deadlift", "deadlifts", "rdl", "romanian"], ["how", "form", "technique", "correct", "properly", "kaise"]], a: "Deadlift form basics:\n\n1. Bar over your **mid-foot**, feet hip-width\n2. Hinge at the hips, grip just outside your knees\n3. **Flat back**: chest up, lats tight (\"squeeze oranges in your armpits\")\n4. Push the floor away with your legs, keep the bar **dragging up your legs**\n5. Stand tall with your glutes; don't lean back\n\nStart light or with Romanian deadlifts using dumbbells. Film yourself from the side to check your back stays flat.", chips: ["Back pain after deadlift"] },
  { id: "bench-form", any: [["bench press", "bench", "chest press"], ["how", "form", "technique", "correct", "properly", "kaise", "shoulder"]], a: "Bench press form:\n\n1. Eyes under the bar, **shoulder blades squeezed together** and down\n2. Feet flat, slight natural arch in your lower back\n3. Grip a little wider than your shoulders\n4. Lower to your **lower chest** with elbows about 45° from your body (not flared out)\n5. Press up and slightly back\n\nAlways use a spotter or safety pins when going heavy." },
  { id: "protein-bar", any: [["protein bar", "energy bar", "protein bars", "packaged", "biscuits", "namkeen"]], a: "Many \"protein\" bars and snacks are candy bars with a little protein. Check the label: aim for **at least 15–20 g protein and under 10 g sugar per bar**. Fine occasionally; everyday options are cheaper: roasted chana, peanuts, curd, boiled eggs, paneer cubes, sprouts chaat." },
  { id: "chicken-paneer", any: [["paneer", "chicken", "soya", "tofu"], ["better", "vs", "or", "which"]], a: "Per 100 g: **chicken breast** has about 31 g protein and 165 kcal (leanest); **soya chunks (dry)** about 52 g protein, cheapest; **paneer** about 18 g protein but about 20 g fat (great but calorie-dense); **tofu** about 8–15 g protein and light. Best choice: whatever fits your diet and budget. Mixing them works great." },
  { id: "soya-safe", strong: true, any: [["soya", "soy", "soybean"], ["safe", "bad", "men", "estrogen", "hormone", "side effect", "harmful", "testosterone"]], a: "Soya is safe for men and women in normal food amounts. Studies show **it doesn't lower testosterone or cause \"man boobs\"** at dietary levels (1–2 servings a day). It's one of the best and cheapest veg proteins. If you have thyroid issues, just keep your intake consistent and follow your doctor's advice." },
  { id: "teens", strong: true, any: [["age 13", "age 14", "age 15", "age 16", "age 17", "teen", "teenager", "school", "under 18", "13 years", "14 years", "15 years", "16 years", "17 years"]], a: "Great that you're starting young! Strength training is **safe for teens** when supervised with good form. It does **not** stunt growth. Focus on bodyweight moves and light weights, learning technique, and playing sports. **Don't diet hard or cut calories.** Eat balanced meals with enough protein, and skip supplements except maybe protein powder if food is hard. Sleep 8–10 hours." },
  { id: "older", strong: true, any: [["40", "45", "50", "55", "60", "65", "70", "old age", "senior", "parents", "mom", "dad", "mother", "father", "elderly"]], a: "It's never too late, and strength training becomes **more** important with age: it protects muscle, bones, balance and blood sugar.\n\n- Start with **2–3 sessions a week**: chair squats, wall or incline push-ups, band rows, step-ups, balance work\n- Daily walking, and gentle yoga for mobility\n- Progress slowly; recovery takes a little longer\n- Enough protein (about 1.2–1.6 g per kg) and vitamin D\n\nWith heart, BP, diabetes or joint conditions, get a doctor's okay first.", chips: ["Beginner home workout", "Yoga for back pain"] },
  { id: "fluctuation", any: [["weight"], ["fluctuat", "up and down", "daily change", "overnight", "increased suddenly", "badh gaya", "gain 1 kg", "1 kg more", "2 kg more"]], a: "Daily weight swings of **1–2 kg are normal**. It's water, salt, carbs, food in your gut, hormones and periods, not fat. To see the real trend, weigh yourself in the morning after the toilet, 3–4 times a week, and compare **weekly averages**. Also check your waist size and photos." },
  { id: "bloating", any: [["bloat", "bloated", "bloating", "gas", "acidity", "constipation", "digestion"]], a: "For bloating, acidity and constipation:\n\n- Increase fibre **slowly** (dal, veggies, fruit) and drink more water\n- Eat slowly; don't lie down right after meals\n- Common triggers: too much whey or lactose, rajma or chole at night, fried or spicy food, carbonated drinks\n- A 10-minute walk after meals really helps\n- Curd or buttermilk supports gut health\n\nSee a doctor for severe pain, blood, weight loss, or symptoms lasting more than a couple of weeks." },
  { id: "cramps", any: [["cramp", "cramps", "muscle cramp", "spasm"]], a: "Muscle cramps usually come from fatigue, dehydration or low electrolytes. Drink enough water (add a pinch of salt or ORS when you sweat a lot), eat potassium-rich foods (banana, coconut water, curd) and magnesium (nuts, seeds), warm up properly, and stretch the muscle gently when it cramps. Frequent night cramps? Check with a doctor." },
  { id: "same-muscle", any: [["same muscle", "every day same", "abs daily", "daily abs", "abs every day", "arms every day", "train daily same"]], a: "Most muscles need **48 hours** to recover after hard training, so train each muscle about **2× a week**, not daily. Abs and calves recover faster, so 3–4 short sessions a week is fine. Doing the same muscle hard every day usually means slower progress, not faster." },
  { id: "morning-cardio", any: [["empty stomach", "fasted cardio", "khali pet"]], a: "Fasted morning cardio isn't better for fat loss than fed cardio; total daily calories decide that. Do it fasted if it feels good, but for weights or intense sessions a small snack (banana, a few dates) usually helps you train harder." },
  { id: "curd", any: [["curd", "dahi", "yogurt", "buttermilk", "chaas"]], a: "Curd is excellent: protein (about 3–4 g per 100 g, or about 10 g for hung curd or Greek yogurt), calcium, and probiotics for your gut. Have it any time, including at night, unless it personally disagrees with you. Buttermilk (chaas) is a great low-calorie drink, especially in summer." },
  { id: "sugar-alternatives", any: [["jaggery", "gur", "honey", "stevia", "brown sugar", "artificial sweetener"]], a: "Jaggery, honey and brown sugar are still sugar, with nearly the same calories. They're just a tiny bit more natural. Use any of them sparingly. Zero-calorie sweeteners like stevia or sucralose are safe in normal amounts and can help if you take a lot of sugar in chai." },
  { id: "chai", any: [["chai", "tea"]], a: "Chai is fine! Watch the sugar: 2 cups a day with 2 tsp sugar each is about 80 extra kcal. Cut to 1 tsp, or use stevia, and have your last cup before about 4 pm so it doesn't hurt sleep. Biscuits with chai add up quickly too." },
  { id: "treadmill-vs-outdoor", any: [["cycling", "swimming", "zumba", "dance", "sports", "badminton", "cricket", "football"]], a: "The best cardio is the one you enjoy and keep doing! Cycling, swimming, dance/Zumba, badminton and football all build stamina and burn calories (about 300–600 kcal an hour depending on intensity). Pair any of them with 2–3 strength sessions a week for the best body composition." },
  { id: "time-short", any: [["only 15", "only 20", "only 10", "short on time", "less time", "no time", "busy schedule", "office", "minutes a day", "20 minutes", "15 minutes", "10 minutes", "20 min", "15 min"]], a: "Short on time? 15–20 minutes still works if you keep it intense:\n\n- **20-Min Full-Body Fat Burn** or **10-Minute Abs** in Body-part workouts\n- At the gym: 3–4 compound exercises as a circuit (squat, push-up or press, row, lunge)\n- Take the stairs and walk during calls to add steps\n\nTwo 20-minute sessions beat zero 60-minute sessions.", chips: ["Make me a 3-day home plan, 20 minutes"] },
];

function lev(a: string, b: string) {
  if (Math.abs(a.length - b.length) > 1) return 2;
  const dp = Array.from({ length: a.length + 1 }, (_, i) => [i, ...Array(b.length).fill(0)]);
  for (let j = 1; j <= b.length; j++) dp[0][j] = j;
  for (let i = 1; i <= a.length; i++)
    for (let j = 1; j <= b.length; j++) dp[i][j] = Math.min(dp[i - 1][j] + 1, dp[i][j - 1] + 1, dp[i - 1][j - 1] + (a[i - 1] === b[j - 1] ? 0 : 1));
  return dp[a.length][b.length];
}

// Real words that are one letter away from a keyword and must not count as typos.
const REAL = new Set(["weight", "height", "light", "night", "right", "fight", "eight", "tight", "might", "sight", "white", "while", "where", "there", "these", "those", "their", "which", "about", "fast", "last", "most", "best", "rest", "test"]);

/** Keyword hit with typo tolerance for single words of 5+ letters ("stamna", "protien"). */
export function fuzzyHas(t: string, words: string[], tokens: string[]) {
  return words.some((w) => {
    if (w.includes(" ")) return t.includes(w);
    if (new RegExp(w.length <= 4 ? `\\b${w}\\b` : `\\b${w}`).test(t)) return true;
    return w.length >= 5 && tokens.some((x) => x.length >= 4 && x[0] === w[0] && !REAL.has(x) && lev(x, w) <= 1);
  });
}

export function matchFaq(t: string): Faq | null {
  const tokens = t.split(" ").filter(Boolean);
  let best: { f: Faq; n: number } | null = null;
  for (const f of FAQ) {
    if (f.any.every((g) => fuzzyHas(t, g, tokens))) {
      const n = f.any.length;
      if (!best || n > best.n) best = { f, n };
    }
  }
  return best?.f ?? null;
}
