// Lists the rendered 3D demos in src/data/moves-3d.ts: move id → number of keyframe stills,
// for the men's model (public/moves3d) and the women's model (public/moves3d/w).
import fs from "node:fs";

function scan(dir) {
  const stills = {};
  if (!fs.existsSync(dir)) return stills;
  for (const f of fs.readdirSync(dir)) {
    const m = f.match(/^(.+)-(\d+)\.webp$/);
    if (m && fs.existsSync(`${dir}/${m[1]}.webp`)) stills[m[1]] = Math.max(stills[m[1]] ?? 0, Number(m[2]) + 1);
  }
  return Object.fromEntries(Object.entries(stills).sort(([a], [b]) => a.localeCompare(b)));
}

export function writeManifest(out = "src/data/moves-3d.ts") {
  const men = scan("public/moves3d");
  const women = scan("public/moves3d/w");
  fs.writeFileSync(
    out,
    `// Generated by scripts/moves3d/manifest.mjs. 3D demos: <id>.webp (animated) and <id>-<n>.webp (keyframe stills).\n` +
      `/** Men's model, in /moves3d */\nexport const MOVES_3D: Record<string, number> = ${JSON.stringify(men, null, 2)};\n\n` +
      `/** Women's model, in /moves3d/w */\nexport const MOVES_3D_W: Record<string, number> = ${JSON.stringify(women, null, 2)};\n`,
  );
  return [Object.keys(men).length, Object.keys(women).length];
}

if (import.meta.url === `file://${process.argv[1]}`) console.log("men / women demos:", writeManifest(...process.argv.slice(2)));
