// Lists the rendered 3D demos (public/moves3d) in src/data/moves-3d.ts: move id → number of keyframe stills.
import fs from "node:fs";

export function writeManifest(dir = "public/moves3d", out = "src/data/moves-3d.ts") {
  const stills = {};
  for (const f of fs.readdirSync(dir)) {
    const m = f.match(/^(.+)-(\d+)\.webp$/);
    if (m && fs.existsSync(`${dir}/${m[1]}.webp`)) stills[m[1]] = Math.max(stills[m[1]] ?? 0, Number(m[2]) + 1);
  }
  const sorted = Object.fromEntries(Object.entries(stills).sort(([a], [b]) => a.localeCompare(b)));
  fs.writeFileSync(out, `// Generated by scripts/moves3d — 3D demos in /public/moves3d: <id>.webp (animated) and <id>-<n>.webp (keyframe stills).\nexport const MOVES_3D: Record<string, number> = ${JSON.stringify(sorted, null, 2)};\n`);
  return Object.keys(sorted).length;
}

if (import.meta.url === `file://${process.argv[1]}`) console.log(writeManifest(...process.argv.slice(2)), "moves");
