// Generated by scripts/fetch-exercise-media.mjs from free-exercise-db (public domain / Unlicense).
export interface ExerciseMedia { frames: string[]; steps: string[]; level: string }
export const EXERCISE_MEDIA: Record<string, ExerciseMedia> = {
  "bench-press": {
    "frames": [
      "/exercises/bench-press-0.webp",
      "/exercises/bench-press-1.webp"
    ],
    "steps": [
      "Lie back on a flat bench. Using a medium width grip (a grip that creates a 90-degree angle in the middle of the movement between the forearms and the upper arms), lift the bar from the rack and hold it straight over you with your arms locked. This will be your starting position.",
      "From the starting position, breathe in and begin coming down slowly until the bar touches your middle chest.",
      "After a brief pause, push the bar back to the starting position as you breathe out. Focus on pushing the bar using your chest muscles. Lock your arms and squeeze your chest in the contracted position at the top of the motion, hold for a second and then start coming down slowly again. Tip: Ideally, lowering the weight should take about twice as long as raising it.",
      "Repeat the movement for the prescribed amount of repetitions."
    ],
    "level": "beginner"
  },
  "incline-db-press": {
    "frames": [
      "/exercises/incline-db-press-0.webp",
      "/exercises/incline-db-press-1.webp"
    ],
    "steps": [
      "Lie back on an incline bench with a dumbbell in each hand atop your thighs. The palms of your hands will be facing each other.",
      "Then, using your thighs to help push the dumbbells up, lift the dumbbells one at a time so that you can hold them at shoulder width.",
      "Once you have the dumbbells raised to shoulder width, rotate your wrists forward so that the palms of your hands are facing away from you. This will be your starting position.",
      "Be sure to keep full control of the dumbbells at all times. Then breathe out and push the dumbbells up with your chest."
    ],
    "level": "beginner"
  },
  "db-bench": {
    "frames": [
      "/exercises/db-bench-0.webp",
      "/exercises/db-bench-1.webp"
    ],
    "steps": [
      "Lie down on a flat bench with a dumbbell in each hand resting on top of your thighs. The palms of your hands will be facing each other.",
      "Then, using your thighs to help raise the dumbbells up, lift the dumbbells one at a time so that you can hold them in front of you at shoulder width.",
      "Once at shoulder width, rotate your wrists forward so that the palms of your hands are facing away from you. The dumbbells should be just to the sides of your chest, with your upper arm and forearm creating a 90 degree angle. Be sure to maintain full control of the dumbbells at all times. This will be your starting position.",
      "Then, as you breathe out, use your chest to push the dumbbells up. Lock your arms at the top of the lift and squeeze your chest, hold for a second and then begin coming down slowly. Tip: Ideally, lowering the weight should take about twice as long as raising it."
    ],
    "level": "beginner"
  },
  "cable-fly": {
    "frames": [
      "/exercises/cable-fly-0.webp",
      "/exercises/cable-fly-1.webp"
    ],
    "steps": [
      "To get yourself into the starting position, place the pulleys on a high position (above your head), select the resistance to be used and hold the pulleys in each hand.",
      "Step forward in front of an imaginary straight line between both pulleys while pulling your arms together in front of you. Your torso should have a small forward bend from the waist. This will be your starting position.",
      "With a slight bend on your elbows in order to prevent stress at the biceps tendon, extend your arms to the side (straight out at both sides) in a wide arc until you feel a stretch on your chest. Breathe in as you perform this portion of the movement. Tip: Keep in mind that throughout the movement, the arms and torso should remain stationary; the movement should only occur at the shoulder joint.",
      "Return your arms back to the starting position as you breathe out. Make sure to use the same arc of motion used to lower the weights."
    ],
    "level": "beginner"
  },
  "push-up": {
    "frames": [
      "/exercises/push-up-0.webp",
      "/exercises/push-up-1.webp"
    ],
    "steps": [
      "Lie on the floor face down and place your hands about 36 inches apart while holding your torso up at arms length.",
      "Next, lower yourself downward until your chest almost touches the floor as you inhale.",
      "Now breathe out and press your upper body back up to the starting position while squeezing your chest.",
      "After a brief pause at the top contracted position, you can begin to lower yourself downward again for as many repetitions as needed."
    ],
    "level": "beginner"
  },
  "dips": {
    "frames": [
      "/exercises/dips-0.webp",
      "/exercises/dips-1.webp"
    ],
    "steps": [
      "For this exercise you will need access to parallel bars. To get yourself into the starting position, hold your body at arms length (arms locked) above the bars.",
      "While breathing in, lower yourself slowly with your torso leaning forward around 30 degrees or so and your elbows flared out slightly until you feel a slight stretch in the chest.",
      "Once you feel the stretch, use your chest to bring your body back to the starting position as you breathe out. Tip: Remember to squeeze the chest at the top of the movement for a second.",
      "Repeat the movement for the prescribed amount of repetitions."
    ],
    "level": "intermediate"
  },
  "deadlift": {
    "frames": [
      "/exercises/deadlift-0.webp",
      "/exercises/deadlift-1.webp"
    ],
    "steps": [
      "Stand in front of a loaded barbell.",
      "While keeping the back as straight as possible, bend your knees, bend forward and grasp the bar using a medium (shoulder width) overhand grip. This will be the starting position of the exercise. Tip: If it is difficult to hold on to the bar with this grip, alternate your grip or use wrist straps.",
      "While holding the bar, start the lift by pushing with your legs while simultaneously getting your torso to the upright position as you breathe out. In the upright position, stick your chest out and contract the back by bringing the shoulder blades back. Think of how the soldiers in the military look when they are in standing in attention.",
      "Go back to the starting position by bending at the knees while simultaneously leaning the torso forward at the waist while keeping the back straight. When the weights on the bar touch the floor you are back at the starting position and ready to perform another repetition."
    ],
    "level": "intermediate"
  },
  "barbell-row": {
    "frames": [
      "/exercises/barbell-row-0.webp",
      "/exercises/barbell-row-1.webp"
    ],
    "steps": [
      "Holding a barbell with a pronated grip (palms facing down), bend your knees slightly and bring your torso forward, by bending at the waist, while keeping the back straight until it is almost parallel to the floor. Tip: Make sure that you keep the head up. The barbell should hang directly in front of you as your arms hang perpendicular to the floor and your torso. This is your starting position.",
      "Now, while keeping the torso stationary, breathe out and lift the barbell to you. Keep the elbows close to the body and only use the forearms to hold the weight. At the top contracted position, squeeze the back muscles and hold for a brief pause.",
      "Then inhale and slowly lower the barbell back to the starting position."
    ],
    "level": "beginner"
  },
  "pull-up": {
    "frames": [
      "/exercises/pull-up-0.webp",
      "/exercises/pull-up-1.webp"
    ],
    "steps": [
      "Grab the pull-up bar with the palms facing forward using the prescribed grip. Note on grips: For a wide grip, your hands need to be spaced out at a distance wider than your shoulder width. For a medium grip, your hands need to be spaced out at a distance equal to your shoulder width and for a close grip at a distance smaller than your shoulder width.",
      "As you have both arms extended in front of you holding the bar at the chosen grip width, bring your torso back around 30 degrees or so while creating a curvature on your lower back and sticking your chest out. This is your starting position.",
      "Pull your torso up until the bar touches your upper chest by drawing the shoulders and the upper arms down and back. Exhale as you perform this portion of the movement. Tip: Concentrate on squeezing the back muscles once you reach the full contracted position. The upper torso should remain stationary as it moves through space and only the arms should move. The forearms should do no other work other than hold the bar.",
      "After a second on the contracted position, start to inhale and slowly lower your torso back to the starting position when your arms are fully extended and the lats are fully stretched."
    ],
    "level": "beginner"
  },
  "lat-pulldown": {
    "frames": [
      "/exercises/lat-pulldown-0.webp",
      "/exercises/lat-pulldown-1.webp"
    ],
    "steps": [
      "Sit down on a pull-down machine with a wide bar attached to the top pulley. Make sure that you adjust the knee pad of the machine to fit your height. These pads will prevent your body from being raised by the resistance attached to the bar.",
      "Grab the bar with the palms facing forward using the prescribed grip. Note on grips: For a wide grip, your hands need to be spaced out at a distance wider than shoulder width. For a medium grip, your hands need to be spaced out at a distance equal to your shoulder width and for a close grip at a distance smaller than your shoulder width.",
      "As you have both arms extended in front of you holding the bar at the chosen grip width, bring your torso back around 30 degrees or so while creating a curvature on your lower back and sticking your chest out. This is your starting position.",
      "As you breathe out, bring the bar down until it touches your upper chest by drawing the shoulders and the upper arms down and back. Tip: Concentrate on squeezing the back muscles once you reach the full contracted position. The upper torso should remain stationary and only the arms should move. The forearms should do no other work except for holding the bar; therefore do not try to pull down the bar using the forearms."
    ],
    "level": "beginner"
  },
  "seated-row": {
    "frames": [
      "/exercises/seated-row-0.webp",
      "/exercises/seated-row-1.webp"
    ],
    "steps": [
      "For this exercise you will need access to a low pulley row machine with a V-bar. Note: The V-bar will enable you to have a neutral grip where the palms of your hands face each other. To get into the starting position, first sit down on the machine and place your feet on the front platform or crossbar provided making sure that your knees are slightly bent and not locked.",
      "Lean over as you keep the natural alignment of your back and grab the V-bar handles.",
      "With your arms extended pull back until your torso is at a 90-degree angle from your legs. Your back should be slightly arched and your chest should be sticking out. You should be feeling a nice stretch on your lats as you hold the bar in front of you. This is the starting position of the exercise.",
      "Keeping the torso stationary, pull the handles back towards your torso while keeping the arms close to it until you touch the abdominals. Breathe out as you perform that movement. At that point you should be squeezing your back muscles hard. Hold that contraction for a second and slowly go back to the original position while breathing in."
    ],
    "level": "beginner"
  },
  "db-row": {
    "frames": [
      "/exercises/db-row-0.webp",
      "/exercises/db-row-1.webp"
    ],
    "steps": [
      "Choose a flat bench and place a dumbbell on each side of it.",
      "Place the right leg on top of the end of the bench, bend your torso forward from the waist until your upper body is parallel to the floor, and place your right hand on the other end of the bench for support.",
      "Use the left hand to pick up the dumbbell on the floor and hold the weight while keeping your lower back straight. The palm of the hand should be facing your torso. This will be your starting position.",
      "Pull the resistance straight up to the side of your chest, keeping your upper arm close to your side and keeping the torso stationary. Breathe out as you perform this step. Tip: Concentrate on squeezing the back muscles once you reach the full contracted position. Also, make sure that the force is performed with the back muscles and not the arms. Finally, the upper torso should remain stationary and only the arms should move. The forearms should do no other work except for holding the dumbbell; therefore do not try to pull the dumbbell up using the forearms."
    ],
    "level": "beginner"
  },
  "face-pull": {
    "frames": [
      "/exercises/face-pull-0.webp",
      "/exercises/face-pull-1.webp"
    ],
    "steps": [
      "Facing a high pulley with a rope or dual handles attached, pull the weight directly towards your face, separating your hands as you do so. Keep your upper arms parallel to the ground."
    ],
    "level": "intermediate"
  },
  "ohp": {
    "frames": [
      "/exercises/ohp-0.webp",
      "/exercises/ohp-1.webp"
    ],
    "steps": [
      "Start by placing a barbell that is about chest high on a squat rack. Once you have selected the weights, grab the barbell using a pronated (palms facing forward) grip. Make sure to grip the bar wider than shoulder width apart from each other.",
      "Slightly bend the knees and place the barbell on your collar bone. Lift the barbell up keeping it lying on your chest. Take a step back and position your feet shoulder width apart from each other.",
      "Once you pick up the barbell with the correct grip length, lift the bar up over your head by locking your arms. Hold at about shoulder level and slightly in front of your head. This is your starting position.",
      "Lower the bar down to the collarbone slowly as you inhale."
    ],
    "level": "beginner"
  },
  "db-shoulder-press": {
    "frames": [
      "/exercises/db-shoulder-press-0.webp",
      "/exercises/db-shoulder-press-1.webp"
    ],
    "steps": [
      "Grab a couple of dumbbells and sit on a military press bench or a utility bench that has a back support on it as you place the dumbbells upright on top of your thighs.",
      "Clean the dumbbells up one at a time by using your thighs to bring the dumbbells up to shoulder height at each side.",
      "Rotate the wrists so that the palms of your hands are facing forward. This is your starting position.",
      "As you exhale, push the dumbbells up until they touch at the top."
    ],
    "level": "beginner"
  },
  "lateral-raise": {
    "frames": [
      "/exercises/lateral-raise-0.webp",
      "/exercises/lateral-raise-1.webp"
    ],
    "steps": [
      "Pick a couple of dumbbells and stand with a straight torso and the dumbbells by your side at arms length with the palms of the hand facing you. This will be your starting position.",
      "While maintaining the torso in a stationary position (no swinging), lift the dumbbells to your side with a slight bend on the elbow and the hands slightly tilted forward as if pouring water in a glass. Continue to go up until you arms are parallel to the floor. Exhale as you execute this movement and pause for a second at the top.",
      "Lower the dumbbells back down slowly to the starting position as you inhale."
    ],
    "level": "beginner"
  },
  "rear-delt-fly": {
    "frames": [
      "/exercises/rear-delt-fly-0.webp",
      "/exercises/rear-delt-fly-1.webp"
    ],
    "steps": [
      "Place a couple of dumbbells looking forward in front of a flat bench.",
      "Sit on the end of the bench with your legs together and the dumbbells behind your calves.",
      "Bend at the waist while keeping the back straight in order to pick up the dumbbells. The palms of your hands should be facing each other as you pick them. This will be your starting position.",
      "Keeping your torso forward and stationary, and the arms slightly bent at the elbows, lift the dumbbells straight to the side until both arms are parallel to the floor. Exhale as you lift the weights. (Note: avoid swinging the torso or bringing the arms back as opposed to the side.)"
    ],
    "level": "intermediate"
  },
  "barbell-curl": {
    "frames": [
      "/exercises/barbell-curl-0.webp",
      "/exercises/barbell-curl-1.webp"
    ],
    "steps": [
      "Stand up with your torso upright while holding a barbell at a shoulder-width grip. The palm of your hands should be facing forward and the elbows should be close to the torso. This will be your starting position.",
      "While holding the upper arms stationary, curl the weights forward while contracting the biceps as you breathe out. Tip: Only the forearms should move.",
      "Continue the movement until your biceps are fully contracted and the bar is at shoulder level. Hold the contracted position for a second and squeeze the biceps hard.",
      "Slowly begin to bring the bar back to starting position as your breathe in."
    ],
    "level": "beginner"
  },
  "hammer-curl": {
    "frames": [
      "/exercises/hammer-curl-0.webp",
      "/exercises/hammer-curl-1.webp"
    ],
    "steps": [
      "Stand up with your torso upright and a dumbbell on each hand being held at arms length. The elbows should be close to the torso.",
      "The palms of the hands should be facing your torso. This will be your starting position.",
      "Now, while holding your upper arm stationary, exhale and curl the weight forward while contracting the biceps. Continue to raise the weight until the biceps are fully contracted and the dumbbell is at shoulder level. Hold the contracted position for a brief moment as you squeeze the biceps. Tip: Focus on keeping the elbow stationary and only moving your forearm.",
      "After the brief pause, inhale and slowly begin the lower the dumbbells back down to the starting position."
    ],
    "level": "beginner"
  },
  "incline-curl": {
    "frames": [
      "/exercises/incline-curl-0.webp",
      "/exercises/incline-curl-1.webp"
    ],
    "steps": [
      "Sit back on an incline bench with a dumbbell in each hand held at arms length. Keep your elbows close to your torso and rotate the palms of your hands until they are facing forward. This will be your starting position.",
      "While holding the upper arm stationary, curl the weights forward while contracting the biceps as you breathe out. Only the forearms should move. Continue the movement until your biceps are fully contracted and the dumbbells are at shoulder level. Hold the contracted position for a second.",
      "Slowly begin to bring the dumbbells back to starting position as your breathe in."
    ],
    "level": "beginner"
  },
  "tricep-pushdown": {
    "frames": [
      "/exercises/tricep-pushdown-0.webp",
      "/exercises/tricep-pushdown-1.webp"
    ],
    "steps": [
      "Attach a rope attachment to a high pulley and grab with a neutral grip (palms facing each other).",
      "Standing upright with the torso straight and a very small inclination forward, bring the upper arms close to your body and perpendicular to the floor. The forearms should be pointing up towards the pulley as they hold the rope with the palms facing each other. This is your starting position.",
      "Using the triceps, bring the rope down as you bring each side of the rope to the side of your thighs. At the end of the movement the arms are fully extended and perpendicular to the floor. The upper arms should always remain stationary next to your torso and only the forearms should move. Exhale as you perform this movement.",
      "After holding for a second, at the contracted position, bring the rope slowly up to the starting point. Breathe in as you perform this step."
    ],
    "level": "beginner"
  },
  "skull-crusher": {
    "frames": [
      "/exercises/skull-crusher-0.webp",
      "/exercises/skull-crusher-1.webp"
    ],
    "steps": [
      "Using a close grip, lift the EZ bar and hold it with your elbows in as you lie on the bench. Your arms should be perpendicular to the floor. This will be your starting position.",
      "Keeping the upper arms stationary, lower the bar by allowing the elbows to flex. Inhale as you perform this portion of the movement. Pause once the bar is directly above the forehead.",
      "Lift the bar back to the starting position by extending the elbow and exhaling.",
      "Repeat."
    ],
    "level": "beginner"
  },
  "overhead-ext": {
    "frames": [
      "/exercises/overhead-ext-0.webp",
      "/exercises/overhead-ext-1.webp"
    ],
    "steps": [
      "To begin, stand up with a dumbbell held by both hands. Your feet should be about shoulder width apart from each other. Slowly use both hands to grab the dumbbell and lift it over your head until both arms are fully extended.",
      "The resistance should be resting in the palms of your hands with your thumbs around it. The palm of the hands should be facing up towards the ceiling. This will be your starting position.",
      "Keeping your upper arms close to your head with elbows in and perpendicular to the floor, lower the resistance in a semicircular motion behind your head until your forearms touch your biceps. Tip: The upper arms should remain stationary and only the forearms should move. Breathe in as you perform this step.",
      "Go back to the starting position by using the triceps to raise the dumbbell. Breathe out as you perform this step."
    ],
    "level": "beginner"
  },
  "back-squat": {
    "frames": [
      "/exercises/back-squat-0.webp",
      "/exercises/back-squat-1.webp"
    ],
    "steps": [
      "This exercise is best performed inside a squat rack for safety purposes. To begin, first set the bar on a rack just above shoulder level. Once the correct height is chosen and the bar is loaded, step under the bar and place the back of your shoulders (slightly below the neck) across it.",
      "Hold on to the bar using both arms at each side and lift it off the rack by first pushing with your legs and at the same time straightening your torso.",
      "Step away from the rack and position your legs using a shoulder-width medium stance with the toes slightly pointed out. Keep your head up at all times and maintain a straight back. This will be your starting position.",
      "Begin to slowly lower the bar by bending the knees and sitting back with your hips as you maintain a straight posture with the head up. Continue down until your hamstrings are on your calves. Inhale as you perform this portion of the movement."
    ],
    "level": "intermediate"
  },
  "front-squat": {
    "frames": [
      "/exercises/front-squat-0.webp",
      "/exercises/front-squat-1.webp"
    ],
    "steps": [
      "This exercise is best performed inside a squat rack for safety purposes. To begin, first set the bar on a rack that best matches your height. Once the correct height is chosen and the bar is loaded, bring your arms up under the bar while keeping the elbows high and the upper arm slightly above parallel to the floor. Rest the bar on top of the deltoids and cross your arms while grasping the bar for total control.",
      "Lift the bar off the rack by first pushing with your legs and at the same time straightening your torso.",
      "Step away from the rack and position your legs using a shoulder width medium stance with the toes slightly pointed out. Keep your head up at all times as looking down will get you off balance and also maintain a straight back. This will be your starting position. (Note: For the purposes of this discussion we will use the medium stance described above which targets overall development; however you can choose any of the three stances described in the foot positioning section).",
      "Begin to slowly lower the bar by bending the knees as you maintain a straight posture with the head up. Continue down until the angle between the upper leg and the calves becomes slightly less than 90-degrees (which is the point in which the upper legs are below parallel to the floor). Inhale as you perform this portion of the movement. Tip: If you performed the exercise correctly, the front of the knees should make an imaginary straight line with the toes that is perpendicular to the front. If your knees are past that imaginary line (if they are past your toes) then you are placing undue stress on the knee and the exercise has been performed incorrectly."
    ],
    "level": "expert"
  },
  "rdl": {
    "frames": [
      "/exercises/rdl-0.webp",
      "/exercises/rdl-1.webp"
    ],
    "steps": [
      "Put a barbell in front of you on the ground and grab it using a pronated (palms facing down) grip that a little wider than shoulder width. Tip: Depending on the weight used, you may need wrist wraps to perform the exercise and also a raised platform in order to allow for better range of motion.",
      "Bend the knees slightly and keep the shins vertical, hips back and back straight. This will be your starting position.",
      "Keeping your back and arms completely straight at all times, use your hips to lift the bar as you exhale. Tip: The movement should not be fast but steady and under control.",
      "Once you are standing completely straight up, lower the bar by pushing the hips back, only slightly bending the knees, unlike when squatting. Tip: Take a deep breath at the start of the movement and keep your chest up. Hold your breath as you lower and exhale as you complete the movement."
    ],
    "level": "intermediate"
  },
  "leg-press": {
    "frames": [
      "/exercises/leg-press-0.webp",
      "/exercises/leg-press-1.webp"
    ],
    "steps": [
      "Using a leg press machine, sit down on the machine and place your legs on the platform directly in front of you at a medium (shoulder width) foot stance. (Note: For the purposes of this discussion we will use the medium stance described above which targets overall development; however you can choose any of the three stances described in the foot positioning section).",
      "Lower the safety bars holding the weighted platform in place and press the platform all the way up until your legs are fully extended in front of you. Tip: Make sure that you do not lock your knees. Your torso and the legs should make a perfect 90-degree angle. This will be your starting position.",
      "As you inhale, slowly lower the platform until your upper and lower legs make a 90-degree angle.",
      "Pushing mainly with the heels of your feet and using the quadriceps go back to the starting position as you exhale."
    ],
    "level": "beginner"
  },
  "bulgarian-split-squat": {
    "frames": [
      "/exercises/bulgarian-split-squat-0.webp",
      "/exercises/bulgarian-split-squat-1.webp"
    ],
    "steps": [
      "Position yourself into a staggered stance with the rear foot elevated and front foot forward.",
      "Hold a dumbbell in each hand, letting them hang at the sides. This will be your starting position.",
      "Begin by descending, flexing your knee and hip to lower your body down. Maintain good posture througout the movement. Keep the front knee in line with the foot as you perform the exercise.",
      "At the bottom of the movement, drive through the heel to extend the knee and hip to return to the starting position."
    ],
    "level": "beginner"
  },
  "walking-lunge": {
    "frames": [
      "/exercises/walking-lunge-0.webp",
      "/exercises/walking-lunge-1.webp"
    ],
    "steps": [
      "Stand with your torso upright holding two dumbbells in your hands by your sides. This will be your starting position.",
      "Step forward with your right leg around 2 feet or so from the foot being left stationary behind and lower your upper body down, while keeping the torso upright and maintaining balance. Inhale as you go down. Note: As in the other exercises, do not allow your knee to go forward beyond your toes as you come down, as this will put undue stress on the knee joint. Make sure that you keep your front shin perpendicular to the ground.",
      "Using mainly the heel of your foot, push up and go back to the starting position as you exhale.",
      "Repeat the movement for the recommended amount of repetitions and then perform with the left leg."
    ],
    "level": "beginner"
  },
  "leg-curl": {
    "frames": [
      "/exercises/leg-curl-0.webp",
      "/exercises/leg-curl-1.webp"
    ],
    "steps": [
      "Adjust the machine lever to fit your height and lie face down on the leg curl machine with the pad of the lever on the back of your legs (just a few inches under the calves). Tip: Preferably use a leg curl machine that is angled as opposed to flat since an angled position is more favorable for hamstrings recruitment.",
      "Keeping the torso flat on the bench, ensure your legs are fully stretched and grab the side handles of the machine. Position your toes straight (or you can also use any of the other two stances described on the foot positioning section). This will be your starting position.",
      "As you exhale, curl your legs up as far as possible without lifting the upper legs from the pad. Once you hit the fully contracted position, hold it for a second.",
      "As you inhale, bring the legs back to the initial position. Repeat for the recommended amount of repetitions."
    ],
    "level": "beginner"
  },
  "leg-extension": {
    "frames": [
      "/exercises/leg-extension-0.webp",
      "/exercises/leg-extension-1.webp"
    ],
    "steps": [
      "For this exercise you will need to use a leg extension machine. First choose your weight and sit on the machine with your legs under the pad (feet pointed forward) and the hands holding the side bars. This will be your starting position. Tip: You will need to adjust the pad so that it falls on top of your lower leg (just above your feet). Also, make sure that your legs form a 90-degree angle between the lower and upper leg. If the angle is less than 90-degrees then that means the knee is over the toes which in turn creates undue stress at the knee joint. If the machine is designed that way, either look for another machine or just make sure that when you start executing the exercise you stop going down once you hit the 90-degree angle.",
      "Using your quadriceps, extend your legs to the maximum as you exhale. Ensure that the rest of the body remains stationary on the seat. Pause a second on the contracted position.",
      "Slowly lower the weight back to the original position as you inhale, ensuring that you do not go past the 90-degree angle limit."
    ],
    "level": "beginner"
  },
  "hip-thrust": {
    "frames": [
      "/exercises/hip-thrust-0.webp",
      "/exercises/hip-thrust-1.webp"
    ],
    "steps": [
      "Begin seated on the ground with a bench directly behind you. Have a loaded barbell over your legs. Using a fat bar or having a pad on the bar can greatly reduce the discomfort caused by this exercise.",
      "Roll the bar so that it is directly above your hips, and lean back against the bench so that your shoulder blades are near the top of it.",
      "Begin the movement by driving through your feet, extending your hips vertically through the bar. Your weight should be supported by your shoulder blades and your feet. Extend as far as possible, then reverse the motion to return to the starting position."
    ],
    "level": "intermediate"
  },
  "calf-raise": {
    "frames": [
      "/exercises/calf-raise-0.webp",
      "/exercises/calf-raise-1.webp"
    ],
    "steps": [
      "Adjust the padded lever of the calf raise machine to fit your height.",
      "Place your shoulders under the pads provided and position your toes facing forward (or using any of the two other positions described at the beginning of the chapter). The balls of your feet should be secured on top of the calf block with the heels extending off it. Push the lever up by extending your hips and knees until your torso is standing erect. The knees should be kept with a slight bend; never locked. Toes should be facing forward, outwards or inwards as described at the beginning of the chapter. This will be your starting position.",
      "Raise your heels as you breathe out by extending your ankles as high as possible and flexing your calf. Ensure that the knee is kept stationary at all times. There should be no bending at any time. Hold the contracted position by a second before you start to go back down.",
      "Go back slowly to the starting position as you breathe in by lowering your heels as you bend the ankles until calves are stretched."
    ],
    "level": "beginner"
  },
  "goblet-squat": {
    "frames": [
      "/exercises/goblet-squat-0.webp",
      "/exercises/goblet-squat-1.webp"
    ],
    "steps": [
      "Stand holding a light kettlebell by the horns close to your chest. This will be your starting position.",
      "Squat down between your legs until your hamstrings are on your calves. Keep your chest and head up and your back straight.",
      "At the bottom position, pause and use your elbows to push your knees out. Return to the starting position, and repeat for 10-20 repetitions."
    ],
    "level": "beginner"
  },
  "plank": {
    "frames": [
      "/exercises/plank-0.webp",
      "/exercises/plank-1.webp"
    ],
    "steps": [
      "Get into a prone position on the floor, supporting your weight on your toes and your forearms. Your arms are bent and directly below the shoulder.",
      "Keep your body straight at all times, and hold this position as long as possible. To increase difficulty, an arm or leg can be raised."
    ],
    "level": "beginner"
  },
  "hanging-leg-raise": {
    "frames": [
      "/exercises/hanging-leg-raise-0.webp",
      "/exercises/hanging-leg-raise-1.webp"
    ],
    "steps": [
      "Hang from a chin-up bar with both arms extended at arms length in top of you using either a wide grip or a medium grip. The legs should be straight down with the pelvis rolled slightly backwards. This will be your starting position.",
      "Raise your legs until the torso makes a 90-degree angle with the legs. Exhale as you perform this movement and hold the contraction for a second or so.",
      "Go back slowly to the starting position as you breathe in."
    ],
    "level": "expert"
  },
  "cable-crunch": {
    "frames": [
      "/exercises/cable-crunch-0.webp",
      "/exercises/cable-crunch-1.webp"
    ],
    "steps": [
      "Kneel below a high pulley that contains a rope attachment.",
      "Grasp cable rope attachment and lower the rope until your hands are placed next to your face.",
      "Flex your hips slightly and allow the weight to hyperextend the lower back. This will be your starting position.",
      "With the hips stationary, flex the waist as you contract the abs so that the elbows travel towards the middle of the thighs. Exhale as you perform this portion of the movement and hold the contraction for a second."
    ],
    "level": "beginner"
  },
  "crunch": {
    "frames": [
      "/exercises/crunch-0.webp",
      "/exercises/crunch-1.webp"
    ],
    "steps": [
      "Lie flat on your back with your feet flat on the ground, or resting on a bench with your knees bent at a 90 degree angle. If you are resting your feet on a bench, place them three to four inches apart and point your toes inward so they touch.",
      "Now place your hands lightly on either side of your head keeping your elbows in. Tip: Don't lock your fingers behind your head.",
      "While pushing the small of your back down in the floor to better isolate your abdominal muscles, begin to roll your shoulders off the floor.",
      "Continue to push down as hard as you can with your lower back as you contract your abdominals and exhale. Your shoulders should come up off the floor only about four inches, and your lower back should remain on the floor. At the top of the movement, contract your abdominals hard and keep the contraction for a second. Tip: Focus on slow, controlled movement - don't cheat yourself by using momentum."
    ],
    "level": "beginner"
  },
  "bicycle-crunch": {
    "frames": [
      "/exercises/bicycle-crunch-0.webp",
      "/exercises/bicycle-crunch-1.webp"
    ],
    "steps": [
      "Lie flat on the floor with your lower back pressed to the ground. For this exercise, you will need to put your hands beside your head. Be careful however to not strain with the neck as you perform it. Now lift your shoulders into the crunch position.",
      "Bring knees up to where they are perpendicular to the floor, with your lower legs parallel to the floor. This will be your starting position.",
      "Now simultaneously, slowly go through a cycle pedal motion kicking forward with the right leg and bringing in the knee of the left leg. Bring your right elbow close to your left knee by crunching to the side, as you breathe out.",
      "Go back to the initial position as you breathe in."
    ],
    "level": "beginner"
  },
  "reverse-crunch": {
    "frames": [
      "/exercises/reverse-crunch-0.webp",
      "/exercises/reverse-crunch-1.webp"
    ],
    "steps": [
      "Lie down on the floor with your legs fully extended and arms to the side of your torso with the palms on the floor. Your arms should be stationary for the entire exercise.",
      "Move your legs up so that your thighs are perpendicular to the floor and feet are together and parallel to the floor. This is the starting position.",
      "While inhaling, move your legs towards the torso as you roll your pelvis backwards and you raise your hips off the floor. At the end of this movement your knees will be touching your chest.",
      "Hold the contraction for a second and move your legs back to the starting position while exhaling."
    ],
    "level": "beginner"
  },
  "flutter-kicks": {
    "frames": [
      "/exercises/flutter-kicks-0.webp",
      "/exercises/flutter-kicks-1.webp"
    ],
    "steps": [
      "On a flat bench lie facedown with the hips on the edge of the bench, the legs straight with toes high off the floor and with the arms on top of the bench holding on to the front edge.",
      "Squeeze your glutes and hamstrings and straighten the legs until they are level with the hips. This will be your starting position.",
      "Start the movement by lifting the left leg higher than the right leg.",
      "Then lower the left leg as you lift the right leg."
    ],
    "level": "beginner"
  },
  "scissor-kicks": {
    "frames": [
      "/exercises/scissor-kicks-0.webp",
      "/exercises/scissor-kicks-1.webp"
    ],
    "steps": [
      "To begin, lie down with your back pressed against the floor or on an exercise mat (optional). Your arms should be fully extended to the sides with your palms facing down. Note: The arms should be stationary the entire time.",
      "With a slight bend at the knees, lift your legs up so that your heels are about 6 inches off the ground. This is the starting position.",
      "Now lift your left leg up to about a 45 degree angle while your right leg is lowered until the heel is about 2-3 inches from the ground.",
      "Switch movements by raising your right leg up and lowering your left leg. Remember to breathe while performing this exercise."
    ],
    "level": "beginner"
  },
  "russian-twist": {
    "frames": [
      "/exercises/russian-twist-0.webp",
      "/exercises/russian-twist-1.webp"
    ],
    "steps": [
      "Lie down on the floor placing your feet either under something that will not move or by having a partner hold them. Your legs should be bent at the knees.",
      "Elevate your upper body so that it creates an imaginary V-shape with your thighs. Your arms should be fully extended in front of you perpendicular to your torso and with the hands clasped. This is the starting position.",
      "Twist your torso to the right side until your arms are parallel with the floor while breathing out.",
      "Hold the contraction for a second and move back to the starting position while breathing out. Now move to the opposite side performing the same techniques you applied to the right side."
    ],
    "level": "intermediate"
  },
  "heel-touch": {
    "frames": [
      "/exercises/heel-touch-0.webp",
      "/exercises/heel-touch-1.webp"
    ],
    "steps": [
      "Lie on the floor with the knees bent and the feet on the floor around 18-24 inches apart. Your arms should be extended by your side. This will be your starting position.",
      "Crunch over your torso forward and up about 3-4 inches to the right side and touch your right heel as you hold the contraction for a second. Exhale while performing this movement.",
      "Now go back slowly to the starting position as you inhale.",
      "Now crunch over your torso forward and up around 3-4 inches to the left side and touch your left heel as you hold the contraction for a second. Exhale while performing this movement and then go back to the starting position as you inhale. Now that both heels have been touched, that is considered 1 repetition."
    ],
    "level": "beginner"
  },
  "mountain-climber": {
    "frames": [
      "/exercises/mountain-climber-0.webp",
      "/exercises/mountain-climber-1.webp"
    ],
    "steps": [
      "Begin in a pushup position, with your weight supported by your hands and toes. Flexing the knee and hip, bring one leg until the knee is approximately under the hip. This will be your starting position.",
      "Explosively reverse the positions of your legs, extending the bent leg until the leg is straight and supported by the toe, and bringing the other foot up with the hip and knee flexed. Repeat in an alternating fashion for 20-30 seconds."
    ],
    "level": "beginner"
  },
  "dead-bug": {
    "frames": [
      "/exercises/dead-bug-0.webp",
      "/exercises/dead-bug-1.webp"
    ],
    "steps": [
      "Begin lying on your back with your hands extended above you toward the ceiling.",
      "Bring your feet, knees, and hips up to 90 degrees.",
      "Exhale hard to bring your ribcage down and flatten your back onto the floor, rotating your pelvis up and squeezing your glutes. Hold this position throughout the movement. This will be your starting position.",
      "Initiate the exercise by extending one leg, straightening the knee and hip to bring the leg just above the ground."
    ],
    "level": "beginner"
  },
  "side-plank": {
    "frames": [
      "/exercises/side-plank-0.webp",
      "/exercises/side-plank-1.webp"
    ],
    "steps": [],
    "level": "beginner"
  },
  "oblique-crunch": {
    "frames": [
      "/exercises/oblique-crunch-0.webp",
      "/exercises/oblique-crunch-1.webp"
    ],
    "steps": [
      "Start out by lying on your right side with your legs lying on top of each other. Make sure your knees are bent a little bit.",
      "Place your left hand behind your head.",
      "Once you are in this set position, begin by moving your left elbow up as you would perform a normal crunch except this time the main emphasis is on your obliques.",
      "Crunch as high as you can, hold the contraction for a second and then slowly drop back down into the starting position."
    ],
    "level": "beginner"
  },
  "jackknife": {
    "frames": [
      "/exercises/jackknife-0.webp",
      "/exercises/jackknife-1.webp"
    ],
    "steps": [
      "Lie flat on the floor (or exercise mat) on your back with your arms extended straight back behind your head and your legs extended also. This will be your starting position.",
      "As you exhale, bend at the waist while simultaneously raising your legs and arms to meet in a jackknife position. Tip: The legs should be extended and lifted at approximately a 35-45 degree angle from the floor and the arms should be extended and parallel to your legs. The upper torso should be off the floor.",
      "While inhaling, lower your arms and legs back to the starting position."
    ],
    "level": "beginner"
  },
  "elbow-to-knee": {
    "frames": [
      "/exercises/elbow-to-knee-0.webp",
      "/exercises/elbow-to-knee-1.webp"
    ],
    "steps": [
      "Lie on the floor, crossing your right leg across your bent left knee. Clasp your hands behind your head, beginning with your shoulder blades on the ground. This will be your starting position.",
      "Perform the motion by flexing the spine and rotating your torso to bring the left elbow to the right knee.",
      "Return to the starting position and repeat the movement for the desired number of repetitions before switching sides."
    ],
    "level": "beginner"
  },
  "glute-bridge": {
    "frames": [
      "/exercises/glute-bridge-0.webp",
      "/exercises/glute-bridge-1.webp"
    ],
    "steps": [
      "Lie flat on the floor on your back with the hands by your side and your knees bent. Your feet should be placed around shoulder width. This will be your starting position.",
      "Pushing mainly with your heels, lift your hips off the floor while keeping your back straight. Breathe out as you perform this part of the motion and hold at the top for a second.",
      "Slowly go back to the starting position as you breathe in."
    ],
    "level": "beginner"
  },
  "single-leg-bridge": {
    "frames": [
      "/exercises/single-leg-bridge-0.webp",
      "/exercises/single-leg-bridge-1.webp"
    ],
    "steps": [
      "Lay on the floor with your feet flat and knees bent.",
      "Raise one leg off of the ground, pulling the knee to your chest. This will be your starting position.",
      "Execute the movement by driving through the heel, extending your hip upward and raising your glutes off of the ground.",
      "Extend as far as possible, pause and then return to the starting position."
    ],
    "level": "beginner"
  },
  "donkey-kick": {
    "frames": [
      "/exercises/donkey-kick-0.webp",
      "/exercises/donkey-kick-1.webp"
    ],
    "steps": [
      "Kneel on the floor or an exercise mat and bend at the waist with your arms extended in front of you (perpendicular to the torso) in order to get into a kneeling push-up position but with the arms spaced at shoulder width. Your head should be looking forward and the bend of the knees should create a 90-degree angle between the hamstrings and the calves. This will be your starting position.",
      "As you exhale, lift up your right leg until the hamstrings are in line with the back while maintaining the 90-degree angle bend. Contract the glutes throughout this movement and hold the contraction at the top for a second. Tip: At the end of the movement the upper leg should be parallel to the floor while the calf should be perpendicular to it.",
      "Go back to the initial position as you inhale and now repeat with the left leg.",
      "Continue to alternate legs until all of the recommended repetitions have been performed."
    ],
    "level": "beginner"
  },
  "side-leg-raise": {
    "frames": [
      "/exercises/side-leg-raise-0.webp",
      "/exercises/side-leg-raise-1.webp"
    ],
    "steps": [
      "Stand next to a chair, which you may hold onto as a support. Stand on one leg. This will be your starting position.",
      "Keeping your leg straight, raise it as far out to the side as possible, and swing it back down, allowing it to cross the opposite leg.",
      "Repeat this swinging motion 5-10 times, increasing the range of motion as you do so."
    ],
    "level": "beginner"
  },
  "rear-leg-raise": {
    "frames": [
      "/exercises/rear-leg-raise-0.webp",
      "/exercises/rear-leg-raise-1.webp"
    ],
    "steps": [
      "Place yourself on your hands knees on an exercise mat. Your head should be looking forward and the bend of the knees should create a 90-degree angle between the hamstrings and the calves. This will be your starting position.",
      "Extend one leg up and behind you. The knee and hip should both extend. Repeat for 5-10 repetitions, and then switch sides."
    ],
    "level": "beginner"
  },
  "bw-squat": {
    "frames": [
      "/exercises/bw-squat-0.webp",
      "/exercises/bw-squat-1.webp"
    ],
    "steps": [
      "Stand with your feet shoulder width apart. You can place your hands behind your head. This will be your starting position.",
      "Begin the movement by flexing your knees and hips, sitting back with your hips.",
      "Continue down to full depth if you are able,and quickly reverse the motion until you return to the starting position. As you squat, keep your head and chest up and push your knees out."
    ],
    "level": "beginner"
  },
  "jump-squat": {
    "frames": [
      "/exercises/jump-squat-0.webp",
      "/exercises/jump-squat-1.webp"
    ],
    "steps": [
      "Cross your arms over your chest.",
      "With your head up and your back straight, position your feet at shoulder width.",
      "Keeping your back straight and chest up, squat down as you inhale until your upper thighs are parallel, or lower, to the floor.",
      "Now pressing mainly with the ball of your feet, jump straight up in the air as high as possible, using the thighs like springs. Exhale during this portion of the movement."
    ],
    "level": "intermediate"
  },
  "bw-lunge": {
    "frames": [
      "/exercises/bw-lunge-0.webp",
      "/exercises/bw-lunge-1.webp"
    ],
    "steps": [
      "Begin standing with your feet shoulder width apart and your hands on your hips.",
      "Step forward with one leg, flexing the knees to drop your hips. Descend until your rear knee nearly touches the ground. Your posture should remain upright, and your front knee should stay above the front foot.",
      "Drive through the heel of your lead foot and extend both knees to raise yourself back up.",
      "Step forward with your rear foot, repeating the lunge on the opposite leg."
    ],
    "level": "beginner"
  },
  "sumo-squat": {
    "frames": [
      "/exercises/sumo-squat-0.webp",
      "/exercises/sumo-squat-1.webp"
    ],
    "steps": [
      "Hold a dumbbell at the base with both hands and stand straight up. Move your legs so that they are wider than shoulder width apart from each other with your knees slightly bent.",
      "Your toes should be facing out. Note: Your arms should be stationary while performing the exercise. This is the starting position.",
      "Slowly bend the knees and lower your legs until your thighs are parallel to the floor. Make sure to inhale as this is the eccentric part of the exercise.",
      "Press mainly with the heel of the foot to bring the body back to the starting position while exhaling."
    ],
    "level": "beginner"
  },
  "step-up": {
    "frames": [
      "/exercises/step-up-0.webp",
      "/exercises/step-up-1.webp"
    ],
    "steps": [
      "Stand facing a box or bench of an appropriate height with your feet together. This will be your starting position.",
      "Begin the movement by stepping up, putting your left foot on the top of the bench. Extend through the hip and knee of your front leg to stand up on the box. As you stand on the box with your left leg, flex your right knee and hip, bringing your knee as high as you can.",
      "Reverse this motion to step down off the box, and then repeat the sequence on the opposite leg."
    ],
    "level": "beginner"
  },
  "bw-calf-raise": {
    "frames": [
      "/exercises/bw-calf-raise-0.webp",
      "/exercises/bw-calf-raise-1.webp"
    ],
    "steps": [
      "Stand with your torso upright holding two dumbbells in your hands by your sides. Place the ball of the foot on a sturdy and stable wooden board (that is around 2-3 inches tall) while your heels extend off and touch the floor. This will be your starting position.",
      "With the toes pointing either straight (to hit all parts equally), inwards (for emphasis on the outer head) or outwards (for emphasis on the inner head), raise the heels off the floor as you exhale by contracting the calves. Hold the top contraction for a second.",
      "As you inhale, go back to the starting position by slowly lowering the heels."
    ],
    "level": "intermediate"
  },
  "incline-push-up": {
    "frames": [
      "/exercises/incline-push-up-0.webp",
      "/exercises/incline-push-up-1.webp"
    ],
    "steps": [
      "Stand facing bench or sturdy elevated platform. Place hands on edge of bench or platform, slightly wider than shoulder width.",
      "Position forefoot back from bench or platform with arms and body straight. Arms should be perpendicular to body. Keeping body straight, lower chest to edge of box or platform by bending arms.",
      "Push body up until arms are extended. Repeat."
    ],
    "level": "beginner"
  },
  "wide-push-up": {
    "frames": [
      "/exercises/wide-push-up-0.webp",
      "/exercises/wide-push-up-1.webp"
    ],
    "steps": [
      "With your hands wide apart, support your body on your toes and hands in a plank position. Your elbows should be extended and your body straight. Do not allow your hips to sag. This will be your starting position.",
      "To begin, allow the elbows to flex, lowering your chest to the floor as you inhale.",
      "Using your pectoral muscles, press your upper body back up to the starting position by extending the elbows. Exhale as you perform this step.",
      "After pausing at the contracted position, repeat the movement for the prescribed amount of repetitions."
    ],
    "level": "beginner"
  },
  "chair-dip": {
    "frames": [
      "/exercises/chair-dip-0.webp",
      "/exercises/chair-dip-1.webp"
    ],
    "steps": [
      "For this exercise you will need to place a bench behind your back. With the bench perpendicular to your body, and while looking away from it, hold on to the bench on its edge with the hands fully extended, separated at shoulder width. The legs will be extended forward, bent at the waist and perpendicular to your torso. This will be your starting position.",
      "Slowly lower your body as you inhale by bending at the elbows until you lower yourself far enough to where there is an angle slightly smaller than 90 degrees between the upper arm and the forearm. Tip: Keep the elbows as close as possible throughout the movement. Forearms should always be pointing down.",
      "Using your triceps to bring your torso up again, lift yourself back to the starting position."
    ],
    "level": "beginner"
  },
  "arm-circles": {
    "frames": [
      "/exercises/arm-circles-0.webp",
      "/exercises/arm-circles-1.webp"
    ],
    "steps": [
      "Stand up and extend your arms straight out by the sides. The arms should be parallel to the floor and perpendicular (90-degree angle) to your torso. This will be your starting position.",
      "Slowly start to make circles of about 1 foot in diameter with each outstretched arm. Breathe normally as you perform the movement.",
      "Continue the circular motion of the outstretched arms for about ten seconds. Then reverse the movement, going the opposite direction."
    ],
    "level": "beginner"
  },
  "towel-tricep": {
    "frames": [
      "/exercises/towel-tricep-0.webp",
      "/exercises/towel-tricep-1.webp"
    ],
    "steps": [
      "To begin, stand up with both arms fully extended above the head holding one end of a towel with both hands. Your elbows should be in and the arms perpendicular to the floor with the palms facing each other while your feet should be shoulder width apart from each other. This is the starting position.",
      "Now communicate with your partner so that he/she can grip the other side of the towel to apply resistance. Keeping your upper arms close to your head (elbows in) and perpendicular to the floor, lower the resistance in a semicircular motion behind your head until your forearms touch your biceps. Tip: The upper arms should remain stationary and only the forearms should move. Breathe in as you perform this step.",
      "Go back to the starting position by using the triceps to raise the towel. Breathe out as you perform this step."
    ],
    "level": "beginner"
  },
  "superman": {
    "frames": [
      "/exercises/superman-0.webp",
      "/exercises/superman-1.webp"
    ],
    "steps": [
      "To begin, lie straight and face down on the floor or exercise mat. Your arms should be fully extended in front of you. This is the starting position.",
      "Simultaneously raise your arms, legs, and chest off of the floor and hold this contraction for 2 seconds. Tip: Squeeze your lower back to get the best results from this exercise. Remember to exhale during this movement. Note: When holding the contracted position, you should look like superman when he is flying.",
      "Slowly begin to lower your arms, legs and chest back down to the starting position while inhaling."
    ],
    "level": "beginner"
  },
  "inchworm": {
    "frames": [
      "/exercises/inchworm-0.webp",
      "/exercises/inchworm-1.webp"
    ],
    "steps": [
      "Stand with your feet close together. Keeping your legs straight, stretch down and put your hands on the floor directly in front of you. This will be your starting position.",
      "Begin by walking your hands forward slowly, alternating your left and your right. As you do so, bend only at the hip, keeping your legs straight.",
      "Keep going until your body is parallel to the ground in a pushup position.",
      "Now, keep your hands in place and slowly take short steps with your feet, moving only a few inches at a time."
    ],
    "level": "beginner"
  },
  "skipping": {
    "frames": [
      "/exercises/skipping-0.webp",
      "/exercises/skipping-1.webp"
    ],
    "steps": [
      "Hold an end of the rope in each hand. Position the rope behind you on the ground. Raise your arms up and turn the rope over your head bringing it down in front of you. When it reaches the ground, jump over it. Find a good turning pace that can be maintained. Different speeds and techniques can be used to introduce variation.",
      "Rope jumping is exciting, challenges your coordination, and requires a lot of energy. A 150 lb person will burn about 350 calories jumping rope for 30 minutes, compared to over 450 calories running."
    ],
    "level": "intermediate"
  },
  "tuck-jump": {
    "frames": [
      "/exercises/tuck-jump-0.webp",
      "/exercises/tuck-jump-1.webp"
    ],
    "steps": [
      "Begin in a comfortable standing position with your knees slightly bent. Hold your hands in front of you, palms down with your fingertips together at chest height. This will be your starting position.",
      "Rapidly dip down into a quarter squat and immediately explode upward. Drive the knees towards the chest, attempting to touch them to the palms of the hands.",
      "Jump as high as you can, raising your knees up, and then ensure a good land be re-extending your legs, absorbing impact through be allowing the knees to rebend."
    ],
    "level": "beginner"
  },
  "neck-side-stretch": {
    "frames": [
      "/exercises/neck-side-stretch-0.webp",
      "/exercises/neck-side-stretch-1.webp"
    ],
    "steps": [
      "Start with your shoulders relaxed, gently tilt your head towards your shoulder.",
      "Assist stretch with a gentle pull on the side of the head."
    ],
    "level": "beginner"
  },
  "neck-isometric": {
    "frames": [
      "/exercises/neck-isometric-0.webp",
      "/exercises/neck-isometric-1.webp"
    ],
    "steps": [
      "With your head and neck in a neutral position (normal position with head erect facing forward), place both of your hands on the front side of your head.",
      "Now gently push forward as you contract the neck muscles but resisting any movement of your head. Start with slow tension and increase slowly. Keep breathing normally as you execute this contraction.",
      "Hold for the recommended number of seconds.",
      "Now release the tension slowly."
    ],
    "level": "beginner"
  },
  "chin-to-chest": {
    "frames": [
      "/exercises/chin-to-chest-0.webp",
      "/exercises/chin-to-chest-1.webp"
    ],
    "steps": [
      "Get into a seated position on the floor.",
      "Place both hands at the rear of your head, fingers interlocked, thumbs pointing down and elbows pointing straight ahead. Slowly pull your head down to your chest. Hold for 20-30 seconds."
    ],
    "level": "beginner"
  },
  "childs-pose": {
    "frames": [
      "/exercises/childs-pose-0.webp",
      "/exercises/childs-pose-1.webp"
    ],
    "steps": [
      "Get on your hands and knees, walk your hands in front of you.",
      "Lower your buttocks down to sit on your heels. Let your arms drag along the floor as you sit back to stretch your entire spine.",
      "Once you settle onto your heels, bring your hands next to your feet and relax. \"breathe\" into your back. Rest your forehead on the floor. Avoid this position if you have knee problems."
    ],
    "level": "beginner"
  },
  "cat-cow": {
    "frames": [
      "/exercises/cat-cow-0.webp",
      "/exercises/cat-cow-1.webp"
    ],
    "steps": [
      "Position yourself on the floor on your hands and knees.",
      "Pull your belly in and round your spine, lower back, shoulders, and neck, letting your head drop.",
      "Hold for 15 seconds."
    ],
    "level": "beginner"
  },
  "knees-to-chest": {
    "frames": [
      "/exercises/knees-to-chest-0.webp",
      "/exercises/knees-to-chest-1.webp"
    ],
    "steps": [
      "Lie down on your back and pull both knees up to your chest.",
      "Hold your arms under the knees, not over (that would put to much pressure on your knee joints).",
      "Slowly pull the knees toward your shoulders. This also stretches your buttocks muscles."
    ],
    "level": "beginner"
  },
  "low-lunge": {
    "frames": [
      "/exercises/low-lunge-0.webp",
      "/exercises/low-lunge-1.webp"
    ],
    "steps": [
      "Kneel on a mat and bring your right knee up so the bottom of your foot is on the floor and extend your left leg out behind you so the top of your foot is on the floor.",
      "Shift your weight forward until you feel a stretch in your hip. Hold for 15 seconds, then repeat for your other side."
    ],
    "level": "beginner"
  },
  "seated-forward-bend": {
    "frames": [
      "/exercises/seated-forward-bend-0.webp",
      "/exercises/seated-forward-bend-1.webp"
    ],
    "steps": [
      "Sit on a mat with your right leg extended in front of you and your left leg bent with your foot against your right inner thigh.",
      "Lean forward from your hips and reach for your ankle until you feel a stretch in your hamstring. Hold for 15 seconds, then repeat for your other side."
    ],
    "level": "beginner"
  },
  "forward-fold": {
    "frames": [
      "/exercises/forward-fold-0.webp",
      "/exercises/forward-fold-1.webp"
    ],
    "steps": [
      "Stand with some space in front and behind you.",
      "Bend at the waist, keeping your legs straight, until you can relax and let your upper body hang down in front of you. Let your arms and hands hang down naturally. Hold for 10 to 20 seconds."
    ],
    "level": "beginner"
  },
  "tadasana": {
    "frames": [
      "/exercises/tadasana-0.webp",
      "/exercises/tadasana-1.webp"
    ],
    "steps": [
      "Extend both hands straight above your head, palms touching.",
      "Slowly push your hands up and back, keeping your back straight."
    ],
    "level": "beginner"
  },
  "worlds-greatest": {
    "frames": [
      "/exercises/worlds-greatest-0.webp",
      "/exercises/worlds-greatest-1.webp"
    ],
    "steps": [
      "This is a three-part stretch. Begin by lunging forward, with your front foot flat on the ground and on the toes of your back foot. With your knees bent, squat down until your knee is almost touching the ground. Keep your torso erect, and hold this position for 10-20 seconds.",
      "Now, place the arm on the same side as your front leg on the ground, with the elbow next to the foot. Your other hand should be placed on the ground, parallel to your lead leg, to help support you during this portion of the stretch.",
      "After 10-20 seconds, place your hands on either side of your front foot. Raise the toes of the front foot off of the ground, and straighten your leg. You may need to reposition your rear leg to do so. Hold for 10-20 seconds, and then repeat the entire sequence for the other side."
    ],
    "level": "intermediate"
  },
  "pelvic-tilt-bridge": {
    "frames": [
      "/exercises/pelvic-tilt-bridge-0.webp",
      "/exercises/pelvic-tilt-bridge-1.webp"
    ],
    "steps": [
      "Lie down with your feet on the floor, heels directly under your knees.",
      "Lift only your tailbone to the ceiling to stretch your lower back. (Don't lift the entire spine yet.) Pull in your stomach.",
      "To go into a bridge, lift the entire spine except the neck."
    ],
    "level": "intermediate"
  }
};
