// Generated by scripts/fetch-move-photos.mjs from free-exercise-db (public domain / Unlicense).
// Start and finish photos for home and yoga moves that have a true photo match.
export const MOVE_PHOTOS: Record<string, [string, string]> = {
  "crunch": [
    "/moves/crunch-0.webp",
    "/moves/crunch-1.webp"
  ],
  "bicycle-crunch": [
    "/moves/bicycle-crunch-0.webp",
    "/moves/bicycle-crunch-1.webp"
  ],
  "reverse-crunch": [
    "/moves/reverse-crunch-0.webp",
    "/moves/reverse-crunch-1.webp"
  ],
  "scissor-kicks": [
    "/moves/scissor-kicks-0.webp",
    "/moves/scissor-kicks-1.webp"
  ],
  "russian-twist": [
    "/moves/russian-twist-0.webp",
    "/moves/russian-twist-1.webp"
  ],
  "heel-touch": [
    "/moves/heel-touch-0.webp",
    "/moves/heel-touch-1.webp"
  ],
  "mountain-climber": [
    "/moves/mountain-climber-0.webp",
    "/moves/mountain-climber-1.webp"
  ],
  "dead-bug": [
    "/moves/dead-bug-0.webp",
    "/moves/dead-bug-1.webp"
  ],
  "plank": [
    "/moves/plank-0.webp",
    "/moves/plank-1.webp"
  ],
  "side-plank": [
    "/moves/side-plank-0.webp",
    "/moves/side-plank-1.webp"
  ],
  "leg-raise": [
    "/moves/leg-raise-0.webp",
    "/moves/leg-raise-1.webp"
  ],
  "oblique-crunch": [
    "/moves/oblique-crunch-0.webp",
    "/moves/oblique-crunch-1.webp"
  ],
  "jackknife": [
    "/moves/jackknife-0.webp",
    "/moves/jackknife-1.webp"
  ],
  "glute-bridge": [
    "/moves/glute-bridge-0.webp",
    "/moves/glute-bridge-1.webp"
  ],
  "single-leg-bridge": [
    "/moves/single-leg-bridge-0.webp",
    "/moves/single-leg-bridge-1.webp"
  ],
  "donkey-kick": [
    "/moves/donkey-kick-0.webp",
    "/moves/donkey-kick-1.webp"
  ],
  "side-leg-raise": [
    "/moves/side-leg-raise-0.webp",
    "/moves/side-leg-raise-1.webp"
  ],
  "rear-leg-raise": [
    "/moves/rear-leg-raise-0.webp",
    "/moves/rear-leg-raise-1.webp"
  ],
  "fire-hydrant": [
    "/moves/fire-hydrant-0.webp",
    "/moves/fire-hydrant-1.webp"
  ],
  "bw-squat": [
    "/moves/bw-squat-0.webp",
    "/moves/bw-squat-1.webp"
  ],
  "jump-squat": [
    "/moves/jump-squat-0.webp",
    "/moves/jump-squat-1.webp"
  ],
  "sumo-squat": [
    "/moves/sumo-squat-0.webp",
    "/moves/sumo-squat-1.webp"
  ],
  "bw-lunge": [
    "/moves/bw-lunge-0.webp",
    "/moves/bw-lunge-1.webp"
  ],
  "step-up": [
    "/moves/step-up-0.webp",
    "/moves/step-up-1.webp"
  ],
  "bw-calf-raise": [
    "/moves/bw-calf-raise-0.webp",
    "/moves/bw-calf-raise-1.webp"
  ],
  "curtsy-lunge": [
    "/moves/curtsy-lunge-0.webp",
    "/moves/curtsy-lunge-1.webp"
  ],
  "incline-push-up": [
    "/moves/incline-push-up-0.webp",
    "/moves/incline-push-up-1.webp"
  ],
  "push-up": [
    "/moves/push-up-0.webp",
    "/moves/push-up-1.webp"
  ],
  "wide-push-up": [
    "/moves/wide-push-up-0.webp",
    "/moves/wide-push-up-1.webp"
  ],
  "chair-dip": [
    "/moves/chair-dip-0.webp",
    "/moves/chair-dip-1.webp"
  ],
  "arm-circles": [
    "/moves/arm-circles-0.webp",
    "/moves/arm-circles-1.webp"
  ],
  "superman": [
    "/moves/superman-0.webp",
    "/moves/superman-1.webp"
  ],
  "towel-tricep": [
    "/moves/towel-tricep-0.webp",
    "/moves/towel-tricep-1.webp"
  ],
  "jumping-jacks": [
    "/moves/jumping-jacks-0.webp",
    "/moves/jumping-jacks-1.webp"
  ],
  "skipping": [
    "/moves/skipping-0.webp",
    "/moves/skipping-1.webp"
  ],
  "tuck-jump": [
    "/moves/tuck-jump-0.webp",
    "/moves/tuck-jump-1.webp"
  ],
  "inchworm": [
    "/moves/inchworm-0.webp",
    "/moves/inchworm-1.webp"
  ],
  "high-knees": [
    "/moves/high-knees-0.webp",
    "/moves/high-knees-1.webp"
  ],
  "neck-side-stretch": [
    "/moves/neck-side-stretch-0.webp",
    "/moves/neck-side-stretch-1.webp"
  ],
  "neck-isometric": [
    "/moves/neck-isometric-0.webp",
    "/moves/neck-isometric-1.webp"
  ],
  "chin-to-chest": [
    "/moves/chin-to-chest-0.webp",
    "/moves/chin-to-chest-1.webp"
  ],
  "childs-pose": [
    "/moves/childs-pose-0.webp",
    "/moves/childs-pose-1.webp"
  ],
  "cat-cow": [
    "/moves/cat-cow-0.webp",
    "/moves/cat-cow-1.webp"
  ],
  "knees-to-chest": [
    "/moves/knees-to-chest-0.webp",
    "/moves/knees-to-chest-1.webp"
  ],
  "worlds-greatest": [
    "/moves/worlds-greatest-0.webp",
    "/moves/worlds-greatest-1.webp"
  ],
  "forward-fold": [
    "/moves/forward-fold-0.webp",
    "/moves/forward-fold-1.webp"
  ],
  "tadasana": [
    "/moves/tadasana-0.webp",
    "/moves/tadasana-1.webp"
  ],
  "low-lunge": [
    "/moves/low-lunge-0.webp",
    "/moves/low-lunge-1.webp"
  ],
  "bridge-pose": [
    "/moves/bridge-pose-0.webp",
    "/moves/bridge-pose-1.webp"
  ],
  "cobra": [
    "/moves/cobra-0.webp",
    "/moves/cobra-1.webp"
  ],
  "plank-yoga": [
    "/moves/plank-yoga-0.webp",
    "/moves/plank-yoga-1.webp"
  ],
  "side-plank-yoga": [
    "/moves/side-plank-yoga-0.webp",
    "/moves/side-plank-yoga-1.webp"
  ],
  "leg-raise-yoga": [
    "/moves/leg-raise-yoga-0.webp",
    "/moves/leg-raise-yoga-1.webp"
  ],
  "supine-twist": [
    "/moves/supine-twist-0.webp",
    "/moves/supine-twist-1.webp"
  ],
  "seated-forward-bend": [
    "/moves/seated-forward-bend-0.webp",
    "/moves/seated-forward-bend-1.webp"
  ]
};
